// Raw hex values — use in non-CSS contexts (SVG props, JS data like LINK_TYPES)
export const rawColors = {
  bgPrimary: "#0f1117",
  bgSecondary: "#1a1d27",
  bgTertiary: "#242836",
  bgCard: "#1e2230",
  border: "#2d3348",
  borderHover: "#3d4460",
  textPrimary: "#e8eaf0",
  textSecondary: "#9ca3b8",
  textMuted: "#6b7290",
  textLight: "#c8cad8",
  accentBlue: "#3b82f6",
  accentBlueDark: "#2563eb",
  accentBlueLighter: "#60a5fa",
  accentGreen: "#10b981",
  accentGreenLighter: "#34d399",
  accentRed: "#ef4444",
  accentRedDark: "#dc2626",
  accentYellow: "#f59e0b",
  accentPurple: "#8b5cf6",
  accentCyan: "#06b6d4",
  accentGray: "#6b7280",
} as const;

// CSS variable references — use in styled-components
export const colors = {
  bgPrimary: "var(--bg-primary)",
  bgSecondary: "var(--bg-secondary)",
  bgTertiary: "var(--bg-tertiary)",
  bgCard: "var(--bg-card)",
  border: "var(--border-color)",
  borderHover: "var(--border-hover)",
  textPrimary: "var(--text-primary)",
  textSecondary: "var(--text-secondary)",
  textMuted: "var(--text-muted)",
  textLight: "var(--text-light)",
  accentBlue: "var(--accent-blue)",
  accentBlueDark: "var(--accent-blue-dark)",
  accentBlueLighter: "var(--accent-blue-lighter)",
  accentGreen: "var(--accent-green)",
  accentGreenLighter: "var(--accent-green-lighter)",
  accentRed: "var(--accent-red)",
  accentRedDark: "var(--accent-red-dark)",
  accentYellow: "var(--accent-yellow)",
  accentPurple: "var(--accent-purple)",
  accentCyan: "var(--accent-cyan)",
  accentGray: "var(--accent-gray)",
  // Alpha variants
  bgCardAlpha90: "var(--bg-card-alpha-90)",
  bgSecondaryAlpha95: "var(--bg-secondary-alpha-95)",
  accentBlueAlpha05: "var(--accent-blue-alpha-05)",
  accentBlueAlpha10: "var(--accent-blue-alpha-10)",
  accentBlueAlpha15: "var(--accent-blue-alpha-15)",
  accentBlueAlpha20: "var(--accent-blue-alpha-20)",
  accentBlueAlpha30: "var(--accent-blue-alpha-30)",
  accentBlueAlpha50: "var(--accent-blue-alpha-50)",
  accentBlueLighterAlpha60: "var(--accent-blue-lighter-alpha-60)",
  accentGreenAlpha10: "var(--accent-green-alpha-10)",
  accentGreenAlpha15: "var(--accent-green-alpha-15)",
  accentGreenLighterAlpha60: "var(--accent-green-lighter-alpha-60)",
  accentRedAlpha15: "var(--accent-red-alpha-15)",
  accentPurpleAlpha10: "var(--accent-purple-alpha-10)",
  accentYellowAlpha10: "var(--accent-yellow-alpha-10)",
  textMutedAlpha15: "var(--text-muted-alpha-15)",
  blackAlpha20: "var(--black-alpha-20)",
  blackAlpha30: "var(--black-alpha-30)",
  blackAlpha40: "var(--black-alpha-40)",
  blackAlpha50: "var(--black-alpha-50)",
} as const;
